transforms: autoaugment_gridmask 
gridmask_r: 0.4
gridmask_minD: 16
gridmask_maxD: 32
gridmask_rotate: 360 

training: vanilla 

epochs: 600 
schedule: step 
steps: [300, 450] 

resume: output/checkpoint.pth.tar
