# Paths
data_path: data/
output_path: output/
gan_weights: AutoGAN/weights/autogan_cifar10_a.pth

# Dataset 
dataset: cifar10
transforms: False

# Training
batch_size: 1
workers: 6
steps: 3000
lr: 0.1
beta1: 0.9
beta2: 0.999

# GAN
z_dim: 128